### ISSUE TITLE
Responsive issue on details (tv and movie)

### ISSUE THREAD

**Issue by tomcayon** [Brize-Glace/tmdb-next#1]
When you go on a details page (no matter tv or movie), you can’t see properly on the informations on the header

### Steps:

1. Go on a film or tv details page
2. then see the non correct behavior

**Comment by Brize-Glace** [comment]
Hello! 
Thansk for your issue.
will work on it asap.
Thanks!

**Comment by Brize-Glace** [comment]
THANKS -- FIXED IN RELEASE 2.1.0
