### ISSUE TITLE
Search tv on home page

### ISSUE THREAD

**Issue by tomcayon** [Brize-Glace/tmdb-next#2]
When you select tv on the search form the search a TV Show/Serie then you search you have to click on “Popular Series” to see the results

### Steps

1. Go on the hompage
2. select TV Show on the search form (be sure the “popular movies” is selected)
3. Search a TV Show/Serie

**Comment by Brize-Glace** [comment]
Hello!
Thansk for your issue.
will work on it asap.
Thanks!

**Comment by Brize-Glace** [comment]
THANKS -- FIXED IN RELEASE 2.1.0
