### ISSUE TITLE
404 page error on clicking on an actor

### ISSUE THREAD

**Issue by tomcayon** [Brize-Glace/tmdb-next#3]
When you click on an actor to see their details it goes on 404 page

### Steps:

1. go on a details page
2. scroll down to the “main characters” section
3. click on an actor

**Comment by Brize-Glace** [comment]
Hello!
Thansk for your issue.
will work on it asap.
Thanks!

**Comment by Brize-Glace** [comment]
THANKS -- FIXED IN RELEASE 2.1.0
